caterwaul.module( 'invariant' , (function( /* unary , node */e_j_uFNUcbF8yIRC8EP5qTjphy) {return(function($) { (function( ) {var deglobalize=e_j_uFNUcbF8yIRC8EP5qTjphy.deglobalize,core_initializer=e_j_uFNUcbF8yIRC8EP5qTjphy.core_initializer,modules=e_j_uFNUcbF8yIRC8EP5qTjphy.modules,module=e_j_uFNUcbF8yIRC8EP5qTjphy.module,merge=e_j_uFNUcbF8yIRC8EP5qTjphy.merge,map=e_j_uFNUcbF8yIRC8EP5qTjphy.map,rmap=e_j_uFNUcbF8yIRC8EP5qTjphy.rmap,gensym=e_j_uFNUcbF8yIRC8EP5qTjphy.gensym,is_gensym=e_j_uFNUcbF8yIRC8EP5qTjphy.is_gensym,syntax_common=e_j_uFNUcbF8yIRC8EP5qTjphy.syntax_common,syntax_subclass=e_j_uFNUcbF8yIRC8EP5qTjphy.syntax_subclass,parse_hex=e_j_uFNUcbF8yIRC8EP5qTjphy.parse_hex,parse_octal=e_j_uFNUcbF8yIRC8EP5qTjphy.parse_octal,unescape_string=e_j_uFNUcbF8yIRC8EP5qTjphy.unescape_string,javascript_tree_type_methods=e_j_uFNUcbF8yIRC8EP5qTjphy.javascript_tree_type_methods,javascript_tree_serialization_methods=e_j_uFNUcbF8yIRC8EP5qTjphy.javascript_tree_serialization_methods,ref_common=e_j_uFNUcbF8yIRC8EP5qTjphy.ref_common,ref=e_j_uFNUcbF8yIRC8EP5qTjphy.ref,expression_ref=e_j_uFNUcbF8yIRC8EP5qTjphy.expression_ref,opaque_tree=e_j_uFNUcbF8yIRC8EP5qTjphy.opaque_tree,syntax=e_j_uFNUcbF8yIRC8EP5qTjphy.syntax,empty=e_j_uFNUcbF8yIRC8EP5qTjphy.empty,parse=e_j_uFNUcbF8yIRC8EP5qTjphy.parse,compile=e_j_uFNUcbF8yIRC8EP5qTjphy.compile,late_bound_tree=e_j_uFNUcbF8yIRC8EP5qTjphy.late_bound_tree,gensym_rename_table=e_j_uFNUcbF8yIRC8EP5qTjphy.gensym_rename_table,init=e_j_uFNUcbF8yIRC8EP5qTjphy.init,initializer=e_j_uFNUcbF8yIRC8EP5qTjphy.initializer,clone=e_j_uFNUcbF8yIRC8EP5qTjphy.clone,replicator=e_j_uFNUcbF8yIRC8EP5qTjphy.replicator,pattern=e_j_uFNUcbF8yIRC8EP5qTjphy.pattern,expander=e_j_uFNUcbF8yIRC8EP5qTjphy.expander,alternatives=e_j_uFNUcbF8yIRC8EP5qTjphy.alternatives,reexpander=e_j_uFNUcbF8yIRC8EP5qTjphy.reexpander,replacer=e_j_uFNUcbF8yIRC8EP5qTjphy.replacer,rereplacer=e_j_uFNUcbF8yIRC8EP5qTjphy.rereplacer,macroexpand=e_j_uFNUcbF8yIRC8EP5qTjphy.macroexpand,anonymizer=e_j_uFNUcbF8yIRC8EP5qTjphy.anonymizer,js=e_j_uFNUcbF8yIRC8EP5qTjphy.js,js_literals=e_j_uFNUcbF8yIRC8EP5qTjphy.js_literals,words=e_j_uFNUcbF8yIRC8EP5qTjphy.words,syntax_to_expression=e_j_uFNUcbF8yIRC8EP5qTjphy.syntax_to_expression,std_initializer=e_j_uFNUcbF8yIRC8EP5qTjphy.std_initializer,js_all=e_j_uFNUcbF8yIRC8EP5qTjphy.js_all,jquery=e_j_uFNUcbF8yIRC8EP5qTjphy.jquery,_environment=e_j_uFNUcbF8yIRC8EP5qTjphy._environment,future_initializer=e_j_uFNUcbF8yIRC8EP5qTjphy.future_initializer,future=e_j_uFNUcbF8yIRC8EP5qTjphy.future;
return($.invariant= (function( ) {var node=function( /* unary , node */behavior) {;
return(function( ) {var n=function( /* unary , node */) {;
return n.send.apply(n,arguments) } ,broadcast=caterwaul.future() ;
return($.merge(n, (function( ) {var to=function(b,p) {;
return(function(it) {return(set_sibling(b,p) ) ,it} ) .call(this, ( (function(it) {return(set_edge(b,p) ) ,it} ) .call(this, (n) ) ) ) } ,send=function(v,visited) {;
return(function( ) {var seen= (function(it) {return(it[id] =n) ,it} ) .call(this, ( (visited|| { } ) ) ) ;
return( (function(it) {return(broadcast(v) ) ,it} ) .call(this, (behavior(n,v,seen) ) ) ) } ) .call(this) } ,unlink=function( /* unary , node */) {;
return(function(it) {return( (function(xs) {var x,x0,xi,xl,xr;
for(var xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] , ( (x) .to(false,n) ) ;
return xs} ) .call(this,siblings) ) ,it} ) .call(this, (n) ) } ,signal=function( /* unary , node */) {;
return broadcast} ,set_edge=function(b,p) {;
return b? (siblings[p.id] =p,p.siblings[id] =n) : (delete siblings[p.id] ,delete p.siblings[id] ) } ,set_sibling=function(b,p) {;
return b?edges[p.id] =p.edges[id] =b: (delete edges[p.id] ,delete p.edges[id] ) } ,id=gensym() ,edges= { } ,siblings= { } ;
return( {to:to,send:send,unlink:unlink,signal:signal,set_edge:set_edge,set_sibling:set_sibling,id:id,edges:edges,siblings:siblings} ) } ) .call(this) ) ) } ) .call(this) } ,node_repeat=function( /* unary , node */) {;
return function(n,v,seen) {;
return(function( ) {var siblings=n.siblings;
return( (future( /* unary , node */ (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( (x[1] (v,seen,siblings[x[0] ] ) ) ) ;
return xr} ) .call(this, (function(o) {var ps= [ ] ;
for(var k in o)Object.prototype.hasOwnProperty.call(o,k) &&ps.push( [k,o[k] ] ) ;
return ps} ) .call(this, ( (function(xs) {var x,x0,xi,xl,xr;
var xr=new xs.constructor() ;
for(var x in xs)if(Object.prototype.hasOwnProperty.call(xs,x) && ! (seen[x] ) )xr[x] =xs[x] ;
return xr} ) .call(this,n.edges) ) ) ) ) ) .map( /* unary , node */function(_) {return v} ) ) } ) .call(this) } } ,node_cache=function( /* unary , node */eq) {;
return function(n,v,seen) {;
return!eq(v,n.val() ) } } ,filter_node=function( /* unary , node */f) {;
return function( /* unary , node */n) {;
return node( (function(v,seen) {return f(v) ?n(v,seen) :future() (v) } ) ) } } ,linear_edge=function(v,visited,n) {;
return n(v,visited) } ,silent_edge=function(v,visited,n) {;
return future() (v) } ,fail_edge=function(v,visited,n) {;
return future() (null) } ;
return( {node:node,node_repeat:node_repeat,node_cache:node_cache,filter_node:filter_node,linear_edge:linear_edge,silent_edge:silent_edge,fail_edge:fail_edge} ) } ) .call(this) ) } ) .call(this) } ) } ) .call(this, /* unary , node */caterwaul) ) ;
